import {BLOCK,INFO} from '../world/Block.js?v=77.7';

/** Chunk-driven passive mob spawner with Minecraft-like distance/cap rules. */
export class MobSpawner{
 constructor(manager,world,quality={}){this.manager=manager;this.world=world;this.interval=quality.tier==='low'?1.8:1.05;this.timer=0;this.passiveCap=quality.tier==='low'?4:6;this.fishCap=quality.tier==='low'?6:12;this.villageKeys=new Set();}
 isDay(time){const phase=(time%720)/720;return phase>=.25&&phase<=.75}
 distanceOK(x,z,p){const d=Math.hypot(x-p.x,z-p.z);return d>=10&&d<=128}
 lightAt(x,y,z,time){if(this.isDay(time))return 15;const xi=Math.floor(x),yi=Math.floor(y),zi=Math.floor(z);let best=0;for(let dx=-8;dx<=8;dx+=2)for(let dy=-3;dy<=3;dy+=2)for(let dz=-8;dz<=8;dz+=2){const info=INFO[this.world.getBlock(xi+dx,yi+dy,zi+dz)];if(info?.emissive)best=Math.max(best,Number(info.light||0)-Math.hypot(dx,dy,dz)*.7)}return best}
 surface(x,z){const xi=Math.floor(x),zi=Math.floor(z);for(let y=this.world.cfg.WORLD.HEIGHT-2;y>=1;y--){const id=this.world.getBlock(xi,y,zi);if(INFO[id]?.solid)return{y:y+1,block:id}}return null}
 nearbyCount(p,predicate){let n=0;for(const m of this.manager.mobs)if(m.alive&&m.pos.distanceTo(p)<=128&&(!predicate||predicate(m)))n++;return n}
 chooseBiome(b){const pool={plains:['chicken','pig','sheep','cow','cow'],birch_grove:['chicken','sheep','cow'],mixed_forest:['chicken','pig','sheep','cow'],jungle:['chicken','pig'],beach:['chicken']}[b]||[];return pool.length?pool[(Math.random()*pool.length)|0]:null}
 tryPassive(player,time){if(!this.isDay(time)||this.nearbyCount(player,m=>['chicken','pig','sheep','cow'].includes(m.type))>=this.passiveCap)return false;const s=this.world.cfg.WORLD.CHUNK_SIZE,pcx=Math.floor(player.pos.x/s),pcz=Math.floor(player.pos.z/s);for(let attempt=0;attempt<8;attempt++){const ccx=pcx+((Math.random()*17|0)-8),ccz=pcz+((Math.random()*17|0)-8),x=ccx*s+(Math.random()*s|0)+.5,z=ccz*s+(Math.random()*s|0)+.5;if(!this.distanceOK(x,z,player))continue;const surf=this.surface(x,z);if(!surf||surf.block!==BLOCK.GRASS)continue;const y=surf.y;if(this.world.getBlock(Math.floor(x),y+1,Math.floor(z))!==BLOCK.AIR)continue;if(this.world.getBlock(Math.floor(x),y+2,Math.floor(z))!==BLOCK.AIR)continue;if(this.lightAt(x,y+1,z,time)<9)continue;const b=this.world.gen.biome(Math.floor(x),Math.floor(z),this.world.gen.height(Math.floor(x),Math.floor(z)));const type=this.chooseBiome(b);if(type&&this.manager.spawnFriendly(x,y,z,type))return true}return false}
 tryFish(player){if(this.nearbyCount(player,m=>m.type==='cod'||m.type==='salmon')>=this.fishCap)return false;const s=this.world.cfg.WORLD.CHUNK_SIZE,pcx=Math.floor(player.pos.x/s),pcz=Math.floor(player.pos.z/s);for(let attempt=0;attempt<10;attempt++){const ccx=pcx+((Math.random()*17|0)-8),ccz=pcz+((Math.random()*17|0)-8),x=ccx*s+(Math.random()*s|0)+.5,z=ccz*s+(Math.random()*s|0)+.5,h=this.world.gen.height(Math.floor(x),Math.floor(z)),b=this.world.gen.biome(Math.floor(x),Math.floor(z),h);if(b!=='ocean'||!this.distanceOK(x,z,player))continue;const y=Math.min(this.world.cfg.WORLD.SEA_LEVEL-1,h+2+((Math.random()*8)|0));if(this.world.getBlock(Math.floor(x),y,Math.floor(z))===BLOCK.AIR||INFO[this.world.getBlock(Math.floor(x),y,Math.floor(z))]?.liquid){const type=Math.random()<.72?'cod':'salmon';if(this.manager.spawnFish(x,y,z,type))return true}}return false}
 spawnVillagersNear(player){const s=this.world.cfg.WORLD.CHUNK_SIZE,pcx=Math.floor(player.pos.x/s),pcz=Math.floor(player.pos.z/s);for(let cx=pcx-4;cx<=pcx+4;cx++)for(let cz=pcz-4;cz<=pcz+4;cz++){const key=`${cx},${cz}`;if(this.villageKeys.has(key))continue;const v=this.world.gen.structures.villageAt(cx,cz);if(!v||!this.world.chunks.has(this.world.key(cx,cz)))continue;const center={x:cx*s+8,z:cz*s+8};if(Math.hypot(center.x-player.x,center.z-player.z)>128)continue;this.villageKeys.add(key);const count=2+((this.world.gen.random(cx,cz,3199)*3)|0);let spawned=0;for(let i=0;i<count;i++){const a=Math.PI*2*i/count,r=2.5+Math.random()*3;const x=center.x+Math.cos(a)*r,z=center.z+Math.sin(a)*r;const surf=this.surface(x,z);if(!surf||!INFO[surf.block]?.solid)continue;const y=surf.y;if(this.world.getBlock(Math.floor(x),y,Math.floor(z))!==BLOCK.AIR&&this.world.getBlock(Math.floor(x),y,Math.floor(z))!==BLOCK.GRASS)continue;if(this.manager.spawnVillager(x,y,z))spawned++;}return spawned>0}return false}
 update(dt,player,time){if(!player)return;this.timer-=dt;if(this.timer>0)return;this.timer=this.interval;this.spawnVillagersNear(player);this.tryPassive(player,time);this.tryFish(player)}
}
