import {ICON,INFO} from "../world/Block.js";

export class RecipeBookUI {
  constructor(game,craftingManager){this.game=game;this.crafting=craftingManager;this.opened=false;this.filter="all";this.signature="";this.timer=0;this.bound=false;this.selectedRecipeId=null}
  setup(){if(this.bound)return;this.bound=true;const close=document.getElementById("recipeBookClose");close?.addEventListener("click",()=>this.close());document.querySelectorAll("[data-recipe-book]").forEach(b=>b.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();this.toggle()}));const all=document.getElementById("recipeFilterAll");const craftable=document.getElementById("recipeFilterCraftable");all?.addEventListener("click",()=>{this.filter="all";this.render()});craftable?.addEventListener("click",()=>{this.filter="craftable";this.render()});document.getElementById("recipeBookQuickCraft")?.addEventListener("click",()=>this.quickCraft())}
  toggle(){this.opened?this.close():this.open()}
  open(){this.opened=true;document.getElementById("recipeBookPanel")?.classList.remove("hidden");this.render();clearInterval(this.timer);this.timer=setInterval(()=>this.refreshIfChanged(),150)}
  close(){this.opened=false;document.getElementById("recipeBookPanel")?.classList.add("hidden");clearInterval(this.timer);this.timer=0}
  refreshIfChanged(){if(!this.opened)return;const s=this.crafting.signature();if(s!==this.signature)this.render()}
  contextLabel(){return this.game.craftMode==="table"?"ВЕРСТАК • 2×2 + 3×3":"ЛИЧНЫЙ КРАФТ • 2×2"}
  render(){if(!this.opened)return;const list=document.getElementById("recipeBookList"),title=document.getElementById("recipeBookContext"),count=document.getElementById("recipeBookCount");if(!list)return;const recipes=this.crafting.recipes();const available=recipes.filter(r=>this.crafting.hasIngredients(r));const shown=this.filter==="craftable"?available:recipes;this.signature=this.crafting.signature();if(title)title.textContent=this.contextLabel();if(count)count.textContent=`${available.length}/${recipes.length} доступно`;
    list.innerHTML="";for(const r of shown){const ready=this.crafting.hasIngredients(r),match=!!this.crafting.findMatch(this.crafting.grid(),[r]);const item=document.createElement("button");item.type="button";item.className=`recipeEntry ${ready?"ready":"locked"}${match?" selected":""}`;item.dataset.recipeId=r.id;item.innerHTML=`<span class="recipeIcon">${ICON[r.out.id]||"·"}</span><span class="recipeText"><strong>${r.name}</strong><small>${INFO[r.out.id]?.name||"Предмет"} ×${r.out.count} • ${r.type==="shaped"?`${r.width}×${r.height}`:"БЕЗ ФОРМЫ"}</small></span><span class="recipeState">${ready?"✓":"—"}</span>`;
      item.addEventListener("click",e=>{e.preventDefault();if(!ready)return;this.selectedRecipeId=r.id;if(e.shiftKey){const made=this.crafting.craftAll(r);this.game.inventoryUI?.render();this.render();if(made)this.game.audio?.block?.();return}if(this.crafting.autoFill(r)){this.game.inventoryUI?.render();this.render()}});list.appendChild(item)};this.updateQuickCraftLabel()
  }
  selectedRecipe(){return this.crafting.recipeManager.getById(this.selectedRecipeId)||null}
  quickCraft(){const recipes=this.crafting.recipes();let r=this.selectedRecipe();if(!r||!recipes.includes(r)||!this.crafting.hasIngredients(r))r=recipes.find(x=>this.crafting.hasIngredients(x))||null;if(!r)return;this.selectedRecipeId=r.id;const made=this.crafting.craftAll(r);this.game.inventoryUI?.render();this.render();if(made)this.game.audio?.block?.()}
  updateQuickCraftLabel(){const b=document.getElementById("recipeBookQuickCraft"),n=document.getElementById("recipeBookSelectedName");const r=this.selectedRecipe();if(n)n.textContent=r?`Выбрано: ${r.name}`:"Выберите рецепт";if(b)b.disabled=!r||!this.crafting.hasIngredients(r)}
}
